version: '3'
services:
  inventory_management:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: npm run docker-compose
    env_file:
        - .env
    ports:
        - "8000:8000"
        - "9239:9239"
    depends_on:
      - mysql_inventory
    restart: on-failure
    volumes:
      - ./:/app

  mysql_inventory:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
      - ./mysql_data:/var/lib/mysql


volumes:
  mysql_data:
