FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

RUN npm install -g nodemon

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the debugging port
EXPOSE 9239
